joomla:
  image: joomla
  links:
    - joomladb:mysql
  ports:
    - 8080:80
  volumes:
    - ./dist/joomla:/var/www/html/templates/ohmj

joomladb:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: example
